### ISSUE TITLE
Minimum git version should be documented

### ISSUE THREAD

**Issue by laouji** [Songmu/ghch#5]
Very minor issue, but I thought I'd mention it anyway.
Older versions of git (for example v1.8.3.1) don't support the -C option:

```
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
```

Would be nice to include what minimum version of git is required somewhere in the documentation

**Comment by Songmu** [comment]
documented at 9027d494c. Thanks!
